dist: xenial
sudo: required
install:
 - sudo apt update
 - sudo apt install golang --allow-unauthenticated -y

before_script:
 - pushd src/backend
 - go get github.com/gorilla/websocket
 - go get github.com/lib/pq
 - popd

script:
 - pushd src/backend
 - go build
 - cd tests && go test -v
