version: '3.5'
services:

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx:/etc/nginx:ro
      - /var/log/docker/nginx/:/var/log/nginx/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - local-web

  collatz:
    restart: unless-stopped
    image: devheaporg/collatz_conjecture:latest-dev
    container_name: collatz
    networks:
      - local-web
    

networks:
  local-web:
    driver: bridge
    name: local-web

