version: '3.5'
services:

  collatz:
    restart: unless-stopped
    image: devheaporg/collatz_conjecture:latest-dev
    container_name: collatz
    ports:
      - "80:80"
    networks:
      - collatz
  
  postgres:
    restart: unless-stopped
    image: postgres:10
    container_name: postgres
    networks:
      - collatz
    environment:
      POSTGRES_PASSWORD: collatz
    volumes:
      - dbdata:/var/lib/postgresql/data

networks:
  collatz:
    driver: bridge
    name: collatz

volumes:
  dbdata:
    name: dbdata
